[2025-02-18T02:21:13.871+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-18T02:21:13.877+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-18T02:21:09.898007+00:00 [queued]>
[2025-02-18T02:21:13.880+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-18T02:21:09.898007+00:00 [queued]>
[2025-02-18T02:21:13.880+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-18T02:21:13.888+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-18 02:21:09.898007+00:00
[2025-02-18T02:21:13.896+0000] {standard_task_runner.py:72} INFO - Started process 346 to run task
[2025-02-18T02:21:13.919+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-18T02:21:09.898007+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmppt38qhk0']
[2025-02-18T02:21:13.926+0000] {standard_task_runner.py:105} INFO - Job 33: Subtask extract_data
[2025-02-18T02:21:14.004+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-18T02:21:09.898007+00:00 [running]> on host f1d396ca8f61
[2025-02-18T02:21:14.086+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-18T02:21:09.898007+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-18T02:21:09.898007+00:00'
[2025-02-18T02:21:14.088+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-18T02:21:14.195+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-18T02:21:14.237+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-18T02:21:18.441+0000] {docker.py:73} INFO - [0m02:21:18  Running with dbt=1.9.2
[2025-02-18T02:21:18.940+0000] {docker.py:73} INFO - [0m02:21:18  Registered adapter: duckdb=1.9.1
[2025-02-18T02:21:19.015+0000] {docker.py:73} INFO - [0m02:21:19  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-18T02:21:20.774+0000] {docker.py:73} INFO - [0m02:21:20  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-18T02:21:20.775+0000] {docker.py:73} INFO - [0m02:21:20
[2025-02-18T02:21:20.776+0000] {docker.py:73} INFO - [0m02:21:20  Concurrency: 1 threads (target='dev')
[2025-02-18T02:21:20.776+0000] {docker.py:73} INFO - [0m02:21:20
[2025-02-18T02:21:24.316+0000] {docker.py:73} INFO - [0m02:21:24  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-18T02:21:51.226+0000] {docker.py:73} INFO - [0m02:21:51  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 26.90s]
[2025-02-18T02:21:51.286+0000] {docker.py:73} INFO - [0m02:21:51
[2025-02-18T02:21:51.287+0000] {docker.py:73} INFO - [0m02:21:51  Finished running 1 table model in 0 hours 0 minutes and 30.51 seconds (30.51s).
[2025-02-18T02:21:51.400+0000] {docker.py:73} INFO - [0m02:21:51
[2025-02-18T02:21:51.400+0000] {docker.py:73} INFO - [0m02:21:51  [32mCompleted successfully[0m
[2025-02-18T02:21:51.401+0000] {docker.py:73} INFO - [0m02:21:51
[2025-02-18T02:21:51.401+0000] {docker.py:73} INFO - [0m02:21:51  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-18T02:21:52.154+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-18T02:21:52.155+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-18T02:21:09.898007+00:00, execution_date=20250218T022109, start_date=20250218T022113, end_date=20250218T022152
[2025-02-18T02:21:52.195+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-18T02:21:52.207+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-18T02:21:52.207+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
