[2025-02-20T14:46:40.592+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T14:46:40.598+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-20T14:44:12.370736+00:00 [queued]>
[2025-02-20T14:46:40.602+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data manual__2025-02-20T14:44:12.370736+00:00 [queued]>
[2025-02-20T14:46:40.602+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-20T14:46:40.612+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-20 14:44:12.370736+00:00
[2025-02-20T14:46:40.616+0000] {standard_task_runner.py:72} INFO - Started process 5367 to run task
[2025-02-20T14:46:40.618+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'manual__2025-02-20T14:44:12.370736+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmpz2autt6v']
[2025-02-20T14:46:40.620+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask extract_data
[2025-02-20T14:46:40.650+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data manual__2025-02-20T14:44:12.370736+00:00 [running]> on host f1d396ca8f61
[2025-02-20T14:46:40.690+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T14:44:12.370736+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T14:44:12.370736+00:00'
[2025-02-20T14:46:40.690+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-20T14:46:40.728+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker_image
[2025-02-20T14:46:40.745+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-20T14:46:43.313+0000] {docker.py:73} INFO - [0m14:46:43  Running with dbt=1.9.2
[2025-02-20T14:46:43.557+0000] {docker.py:73} INFO - [0m14:46:43  Registered adapter: duckdb=1.9.1
[2025-02-20T14:46:43.624+0000] {docker.py:73} INFO - [0m14:46:43  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-20T14:46:44.767+0000] {docker.py:73} INFO - [0m14:46:44  Found 1 model, 1 seed, 19 data tests, 424 macros
[2025-02-20T14:46:44.768+0000] {docker.py:73} INFO - [0m14:46:44
[2025-02-20T14:46:44.768+0000] {docker.py:73} INFO - [0m14:46:44  Concurrency: 1 threads (target='dev')
[2025-02-20T14:46:44.769+0000] {docker.py:73} INFO - [0m14:46:44
[2025-02-20T14:46:46.225+0000] {docker.py:73} INFO - [0m14:46:46  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-20T14:47:13.119+0000] {docker.py:73} INFO - [0m14:47:13  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 26.89s]
[2025-02-20T14:47:13.187+0000] {docker.py:73} INFO - [0m14:47:13
[2025-02-20T14:47:13.188+0000] {docker.py:73} INFO - [0m14:47:13  Finished running 1 table model in 0 hours 0 minutes and 28.42 seconds (28.42s).
[2025-02-20T14:47:13.305+0000] {docker.py:73} INFO - [0m14:47:13
[2025-02-20T14:47:13.305+0000] {docker.py:73} INFO - [0m14:47:13  [32mCompleted successfully[0m
[2025-02-20T14:47:13.306+0000] {docker.py:73} INFO - [0m14:47:13
[2025-02-20T14:47:13.306+0000] {docker.py:73} INFO - [0m14:47:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-20T14:47:14.019+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-20T14:47:14.020+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=manual__2025-02-20T14:44:12.370736+00:00, execution_date=20250220T144412, start_date=20250220T144640, end_date=20250220T144714
[2025-02-20T14:47:14.056+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T14:47:14.081+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-20T14:47:14.083+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
