[2025-02-16T00:13:10.460+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T00:13:10.465+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-15T00:00:00+00:00 [queued]>
[2025-02-16T00:13:10.469+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_climate.extract_data scheduled__2025-02-15T00:00:00+00:00 [queued]>
[2025-02-16T00:13:10.469+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-16T00:13:10.478+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): extract_data> on 2025-02-15 00:00:00+00:00
[2025-02-16T00:13:10.482+0000] {standard_task_runner.py:72} INFO - Started process 433 to run task
[2025-02-16T00:13:10.486+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_climate', 'extract_data', 'scheduled__2025-02-15T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/climate_extract_dag.py', '--cfg-path', '/tmp/tmp15j37ds3']
[2025-02-16T00:13:10.488+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask extract_data
[2025-02-16T00:13:10.519+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_climate.extract_data scheduled__2025-02-15T00:00:00+00:00 [running]> on host 4360a910c8ec
[2025-02-16T00:13:10.619+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_climate' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-15T00:00:00+00:00'
[2025-02-16T00:13:10.620+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-16T00:13:10.671+0000] {docker.py:379} INFO - Starting docker container from image dbt_docker
[2025-02-16T00:13:10.692+0000] {docker.py:387} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-16T00:13:13.036+0000] {docker.py:73} INFO - [0m00:13:13  Running with dbt=1.9.2
[2025-02-16T00:13:13.235+0000] {docker.py:73} INFO - [0m00:13:13  Registered adapter: duckdb=1.9.1
[2025-02-16T00:13:13.286+0000] {docker.py:73} INFO - [0m00:13:13  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-02-16T00:13:14.392+0000] {docker.py:73} INFO - [0m00:13:14  Found 2 models, 1 seed, 28 data tests, 424 macros
[2025-02-16T00:13:14.394+0000] {docker.py:73} INFO - [0m00:13:14
[2025-02-16T00:13:14.394+0000] {docker.py:73} INFO - [0m00:13:14  Concurrency: 1 threads (target='dev')
[2025-02-16T00:13:14.394+0000] {docker.py:73} INFO - [0m00:13:14
[2025-02-16T00:13:17.114+0000] {docker.py:73} INFO - [0m00:13:17  1 of 1 START sql table model main.open_meteo_raw_data .......................... [RUN]
[2025-02-16T00:43:46.029+0000] {job.py:229} INFO - Heartbeat recovered after 1810.29 seconds
[2025-02-16T00:43:52.582+0000] {docker.py:73} INFO - [0m00:43:52  1 of 1 OK created sql table model main.open_meteo_raw_data ..................... [[32mOK[0m in 1835.45s]
[2025-02-16T00:43:52.657+0000] {docker.py:73} INFO - [0m00:43:52
[2025-02-16T00:43:52.658+0000] {docker.py:73} INFO - [0m00:43:52  Finished running 1 table model in 0 hours 30 minutes and 38.26 seconds (1838.26s).
[2025-02-16T00:43:52.806+0000] {docker.py:73} INFO - [0m00:43:52
[2025-02-16T00:43:52.806+0000] {docker.py:73} INFO - [0m00:43:52  [32mCompleted successfully[0m
[2025-02-16T00:43:52.807+0000] {docker.py:73} INFO - [0m00:43:52
[2025-02-16T00:43:52.807+0000] {docker.py:73} INFO - [0m00:43:52  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-16T00:43:53.408+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-16T00:43:53.409+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_climate, task_id=extract_data, run_id=scheduled__2025-02-15T00:00:00+00:00, execution_date=20250215T000000, start_date=20250216T001310, end_date=20250216T004353
[2025-02-16T00:43:53.448+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T00:43:53.467+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-16T00:43:53.468+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
